title: Mousa Karayanni
url: 'https://mousakr.github.io' # the base hostname & protocol for your site, e.g. http://example.com
twitter: KarayanniMousa
github: mousakr
author: Mousa Karayanni

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - _pages
# Other options
# permalink: blog/:year/:month/:title

